apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: aws-sqs
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: aws-sqs
      eventName: example
  triggers:
    - template:
        name: sqs-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: aws-sqs-workflow-
              spec:
                entrypoint: entry-point-data-first-workflow
                arguments:
                  parameters:
                  - name: arg0
                    value: "{{workflow.name}}"
                  - name: arg1
                    value: Hello2
                  - name: arg2
                    value: Afaque2
                templates:
                - name: entry-point-data-first-workflow
                  container:
                    image: mozafaq/account-city-amount:20220402.1
                    command: [/app/execution.py]
                    args: ["{{workflow.parameters.arg0}}", "{{workflow.parameters.arg1}}", "{{workflow.parameters.arg2}}"]
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body
              dest: spec.arguments.parameters.2.value
